import { useEffect,useRef,useState,useSyncExternalStore,type ChangeEvent } from 'react';
import type { Session,SupabaseClient } from '@supabase/supabase-js';
import { activeNodes,gateState,LABELS,LEVEL_HELP,LEVELS,nextWaypoint,SIGNALS,type Tab,type TrailNode } from './domain';
import { configuredClient,createService,initializeSession,signIn,type ImportPreview } from './service';
import { AccountStore } from './store';
import { prepareImport } from './imports';
import { ImportSubmission } from './import-submission';
import { registerWebMCP } from './webmcp';
import { Modal } from './components/Modal';
import { ConceptGraph } from './components/ConceptGraph';
import { TrailEditor } from './components/TrailEditor';
import { LensToolbar,TrailMap,Terrain } from './components/TrailMap';
import { Notes } from './components/Notes';
import { Deferred,ProjectScenario } from './components/Guidance';

export function Brand(){return <div className="brand"><img src={`${import.meta.env.BASE_URL}vesserith.svg`} width="48" height="48" alt=""/><div><p className="eyebrow">YOUR LEARNING OBSERVATORY</p><span>VESSERITH</span></div></div>;}
function download(value:unknown){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`vesserith-context-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function App(){
  const [client]=useState(()=>configuredClient()),[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[store,setStore]=useState<AccountStore|null>(null);
  useEffect(()=>{if(!client){setLoading(false);return;}let live=true;
    initializeSession(client).then(s=>{if(live)setSession(s);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});
    const {data}=client.auth.onAuthStateChange((_event,next)=>{if(live)setSession(next);});return()=>{live=false;data.subscription.unsubscribe();};
  },[client]);
  useEffect(()=>{if(!client||!session){setStore(null);return;}const s=new AccountStore(session.user.id,createService(client));setStore(s);void s.start();return()=>s.stop();},[client,session?.user.id]);
  useEffect(()=>{if(session&&store)store.reauthenticated();},[session?.access_token]);
  const login=async()=>{if(!client)return;const {error}=await signIn(client);if(error)setError(error.message);};
  if(!loading&&store&&session&&client)return <Workspace store={store} identity={session.user.user_metadata.user_name??session.user.user_metadata.name??'Learner'} onSignOut={async()=>{const {error}=await client.auth.signOut({scope:'local'});if(error)throw error;}} onSignIn={()=>void login()}/>;
  return <div className="signin-page"><header><Brand/><span className="version">v3.0.0</span></header><main className="signin-layout"><section><p className="eyebrow">A PLACE TO MAKE KNOWLEDGE YOURS</p><h1>Find your path.<br/><em>Build your understanding.</em></h1><p className="signin-lead">One private learning trail. Your notes, progress, and next steps—together wherever you return.</p><button className="primary signin-button" disabled={loading||!client} onClick={()=>void login()}>{loading?'Restoring your session…':'Sign in with GitHub ↗'}</button>{!client&&<p className="warning">Account services are not configured for this build yet. No workspace data is loaded or saved.</p>}{error&&<p role="alert" className="warning">{error}</p>}<p className="small">Identity only. Vesserith does not request access to your repositories.</p><div className="signin-benefits"><span>01 / Your own map</span><span>02 / Notes that follow you</span><span>03 / Room to explore</span></div></section><div className="signin-terrain" aria-hidden="true"><Terrain/><svg viewBox="0 0 500 580"><path d="M60 460C160 440 160 310 220 350S300 280 340 200 400 260 445 110"/>{[[60,460],[160,370],[220,350],[290,290],[340,200],[445,110]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="20"/><circle cx={x} cy={y} r="12"/><text x={x} y={y+4} textAnchor="middle">{String(i).padStart(2,'0')}</text></g>)}</svg><span className="terrain-caption">A living map, made personal.</span></div></main><footer>Vesserith · Private by account · Built for a deliberate learning journey</footer></div>;
}

export function Workspace({store,identity,onSignOut,onSignIn}:{store:AccountStore;identity:string;onSignOut:()=>Promise<void>;onSignIn:()=>void}){
  const view=useSyncExternalStore(store.subscribe,store.getSnapshot),state=view.state,ui=view.ui;
  const [edit,setEdit]=useState(false),[editing,setEditing]=useState(false),[account,setAccount]=useState(false),[logout,setLogout]=useState(false),[message,setMessage]=useState(''),[importPreview,setImportPreview]=useState<ImportPreview|null>(null),[choices,setChoices]=useState<Record<string,boolean>>({}),[focusToken,setFocusToken]=useState(0),[reviewQueue,setReviewQueue]=useState(false);
  const fileInput=useRef<HTMLInputElement>(null),panel=useRef<HTMLElement>(null),bookmarkApplied=useRef(false),importSubmission=useRef<ImportSubmission|null>(null);
  const [importPending,setImportPending]=useState(false),[importError,setImportError]=useState('');
  useEffect(()=>state?registerWebMCP(store):undefined,[store,!!state]);
  useEffect(()=>{store.setBusy('modal',edit||account||logout||!!importPreview||reviewQueue||ui.concept.open);return()=>store.setBusy('modal',false);},[edit,account,logout,importPreview,reviewQueue,ui.concept.open]);
  useEffect(()=>{if(!state)return;if(!bookmarkApplied.current){bookmarkApplied.current=true;const id=new URLSearchParams(location.hash.replace(/^#\/?/,'')).get('waypoint');if(id&&state.graph.nodes.some(n=>n.id===id))store.updateUI({selected:id});return;}if(ui.selected)history.replaceState(null,'',`${import.meta.env.BASE_URL}#waypoint=${encodeURIComponent(ui.selected)}`);},[!!state,ui.selected]);
  useEffect(()=>{const onHash=()=>{const id=new URLSearchParams(location.hash.replace(/^#\/?/,'')).get('waypoint');if(id&&store.getSnapshot().state?.graph.nodes.some(n=>n.id===id))store.updateUI({selected:id});};window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash);},[store]);
  const exportWork=async()=>{await store.flush();download(store.export());setMessage('Private context exported, including any pending recovery work. Keep this file private.');};
  const signout=async()=>{try{if(!(await store.flush())){setLogout(true);return;}await onSignOut();}catch(e){setMessage(e instanceof Error?e.message:String(e));setLogout(true);}};
  const select=async(id:string)=>{void store.flush();store.updateUI({selected:id,expanded:false});if(panel.current){panel.current.focus({preventScroll:true});if(!matchMedia('(prefers-reduced-motion: reduce)').matches)panel.current.animate([{outlineColor:'#6be4ed'},{outlineColor:'transparent'}],{duration:240});panel.current.scrollIntoView({block:'nearest',behavior:'instant'});}};
  const importFile=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file||!state)return;try{if(file.size>60_000_000)throw new Error('This context file exceeds the 60 MB limit.');if(!(await store.flush()))throw new Error('Resolve or export pending changes before previewing an import.');const bundle=prepareImport(JSON.parse(await file.text()),store.getSnapshot().state!);const preview=await store.service.previewImport(bundle);setChoices(Object.fromEntries(preview.fields.map(f=>[f.key,!f.conflict])));importSubmission.current=new ImportSubmission(store.service,preview.id);setImportError('');setImportPreview(preview);setAccount(false);}catch(e){setMessage(e instanceof Error?e.message:String(e));}};
  const applyImport=async()=>{if(!importSubmission.current||importPending)return;setImportPending(true);setImportError('');try{const result=await importSubmission.current.commit(choices);if(!result.ok)throw new Error(result.message);await store.forceRefresh();setImportPreview(null);setMessage('Reviewed context imported. Original source copies were not modified.');}catch(e){setImportError(e instanceof Error?e.message:String(e));}finally{setImportPending(false);}};
  if(!state)return <div className="loading-shell"><Brand/><h1>{view.error?'Your account could not load':'Opening your observatory…'}</h1><p role="status">{view.error||view.status}</p><button onClick={()=>void store.start()}>Retry account loading</button><button onClick={onSignIn}>Sign in again</button></div>;
  const nodes=activeNodes(state.graph),selected=state.graph.nodes.find(n=>n.id===ui.selected&&!n.archived)??nodes[0],next=nextWaypoint(state),model=state.graph.nodes.find(n=>n.origin==='model'&&!n.archived),stageIndex=nodes.filter(n=>n.kind==='stage').findIndex(n=>n.id===selected?.id);
  const writeConcept=()=>{if(model){store.updateUI({selected:model.id,tab:'notes',concept:{...ui.concept,open:false}});setFocusToken(t=>t+1);}};
  return <div className="app-shell"><a className="skip-link" href="#workspace">Skip to your workspace</a><header className="top-hud"><Brand/><div className="header-actions"><button className="continue" onClick={()=>{if(next)void select(next.id);}}><span className="eyebrow">CONTINUE YOUR EXPEDITION ↗</span><strong>{next?.kind==='gate'?`Gate ${next.code} · ${gateState(next,state.graph,state.learning).label}`:next?.title??'Create your first stage'}</strong></button><button className="account-trigger" onClick={()=>setAccount(true)} aria-label="Open account menu">{identity.slice(0,1).toUpperCase()}<span>Account</span></button></div></header>
    <section className="mission"><div><span className="eyebrow">UP NEXT</span><p>{next?.kind==='stage'?next.content.action:'Rebuild, explain, and diagnose the pair in your gate self-test.'}</p></div><details open={ui.about} onToggle={e=>{if(e.currentTarget.open!==ui.about)store.updateUI({about:e.currentTarget.open});}}><summary>About this expedition</summary><p>Learn the Python MCP pattern, then apply it to a bounded project question. Your template is editable; notes and ratings are private to your account. A ready gate opens a self-test, not a certification.</p></details></section>
    <div className="workspace-status"><span role="status" className={view.error||view.expired||view.draftFailure?'warning':''}>{view.status}</span>{view.expired&&<button onClick={onSignIn}>Reauthenticate</button>}{view.queue.some(q=>q.conflict||q.error)&&<button onClick={()=>setReviewQueue(true)}>Review pending changes</button>}<div><button aria-pressed={editing} onClick={()=>setEditing(!editing)}>{editing?'Finish placing':'Edit trail'}</button>{editing&&<button onClick={()=>setEdit(true)}>Manage stages, gates & routes</button>}</div></div>
    {message&&<p role="status" className="notice">{message}<button aria-label="Dismiss message" onClick={()=>setMessage('')}>×</button></p>}
    <main id="workspace" className="workspace"><section className="map-panel" aria-label="Personal trail map"><LensToolbar state={state} lens={ui.lens} onChange={lens=>store.updateUI({lens})}/><TrailMap state={state} selected={ui.selected} lens={ui.lens} onSelect={id=>void select(id)} editing={editing} store={store}/><Deferred open={ui.deferred} onChange={deferred=>store.updateUI({deferred})}/></section>
      <aside ref={panel} tabIndex={-1} className="detail-panel" aria-label="Selected waypoint workspace">{selected?<><div className="detail-heading"><p className="eyebrow">{selected.kind==='stage'?`STAGE ${String(stageIndex).padStart(2,'0')} / ${SIGNALS.every(s=>state.learning.mastery[selected.id]?.[s]?.value==='independent')?'INDEPENDENT':'IN PROGRESS'}`:`${selected.kind.toUpperCase()} ${selected.code}`}</p><h1>{selected.title}</h1>{!selected.placed&&<p className="warning">Unplaced draft · not counted in progress</p>}</div>
      {selected.kind==='stage'?<><StageTabs tab={ui.tab} onChange={tab=>{void store.flush();store.updateUI({tab});}}/><div hidden={ui.tab!=='brief'} role="tabpanel" id="panel-brief" aria-labelledby="tab-brief"><section className="next-action"><p className="eyebrow">NEXT ACTION</p><p>{selected.content.action||'Add a next action in Edit trail.'}</p></section>{selected.origin==='model'&&<button className="concept-entry" onClick={()=>store.updateUI({concept:{...ui.concept,open:true}})}><span className="eyebrow">INTERACTIVE MENTAL MODEL</span><strong>Explore the MCP concept map ↗</strong></button>}<dl><dt>Objective</dt><dd>{selected.content.objective}</dd><dt>Success evidence</dt><dd>{selected.content.evidence}</dd></dl></div>
      <div hidden={ui.tab!=='self-check'} role="tabpanel" id="panel-self-check" aria-labelledby="tab-self-check"><p className="muted">Set each signal from evidence, not confidence alone.</p>{SIGNALS.map((signal,i)=><fieldset key={signal} className={`mastery-card signal-${signal}`}><legend>{signal[0].toUpperCase()+signal.slice(1)}</legend><p>{['Do I understand how this stage works?','Can I carry out this stage’s action?','Can I explain this stage in my own words?'][i]}</p><div className="level-options">{LEVELS.map((level,j)=><label key={level}><input type="radio" name={`${selected.id}:${signal}`} value={level} checked={state.learning.mastery[selected.id]?.[signal]?.value===level} onChange={()=>void store.mastery(selected.id,signal,level).catch(e=>setMessage(e.message))}/><span><strong>{LABELS[level]}</strong><small>{LEVEL_HELP[j]}</small></span></label>)}</div></fieldset>)}</div>
      <div hidden={ui.tab!=='notes'} role="tabpanel" id="panel-notes" aria-labelledby="tab-notes"><Notes key={selected.id} stage={selected} store={store} expanded={ui.expanded} onExpand={expanded=>store.updateUI({expanded})} focusToken={focusToken}/></div></>:selected.kind==='gate'?<GateDetails node={selected} state={state}/>:<><dl><dt>Choose when</dt><dd>{selected.content.choose}</dd><dt>Outcome</dt><dd>{selected.content.outcome}</dd><dt>Constraint</dt><dd>{selected.content.constraint}</dd></dl>{selected.origin==='pymynyra'&&<ProjectScenario/>}</>}
      {editing&&<button onClick={()=>setEdit(true)}>Edit trail elements</button>}</>:<p>Add your first stage in Edit trail.</p>}</aside></main>
    <footer className="app-footer"><span>VESSERITH <span className="version">v3.0.0</span></span><span>Your trail is private to your account.</span></footer>
    <ConceptGraph selection={ui.concept} update={concept=>store.updateUI({concept})} onWrite={writeConcept}/><TrailEditor open={edit} onClose={()=>setEdit(false)} state={state} store={store}/>
    <input ref={fileInput} hidden type="file" accept="application/json,.json" onChange={e=>void importFile(e)}/>
    <Modal open={account} title="Your account" onClose={()=>setAccount(false)}><h3>{identity}</h3><p>{view.status}</p><p className="muted">Learning data belongs to this account, not to this browser. GitHub supplies your identity; it does not receive your notes.</p><div className="account-actions"><button onClick={()=>void exportWork()}>Export my context</button><button onClick={()=>fileInput.current?.click()}>Import context…</button><button onClick={()=>void signout()}>Sign out of this browser</button></div></Modal>
    <Modal open={logout} title="Some changes are not saved" onClose={()=>setLogout(false)}><p>Stay signed in to retry, or export a recovery copy before leaving. Drafts remain scoped to this account and cannot be replayed into another account.</p><button className="primary" onClick={()=>setLogout(false)}>Remain signed in</button><button onClick={async()=>{download(store.export());try{await onSignOut();}catch(e){setMessage(e instanceof Error?e.message:String(e));}}}>Export pending work and sign out</button></Modal>
    <Modal open={!!importPreview} title="Review your context import" className="import-modal" onClose={()=>{if(!importPending)setImportPreview(null);}}><p>Existing account work is retained by default when values differ. An empty note may be an intentional clearing. Select only the incoming fields you want to apply.</p>{importError&&<p role="alert" className="warning">{importError} Retry uses the same reviewed choices. To change them, close this review and preview the file again.</p>}<button disabled={!!importSubmission.current?.submitted} onClick={()=>{if(importPreview)setChoices(Object.fromEntries(importPreview.fields.map(f=>[f.key,true])));}}>Select all incoming values</button>{importPreview?.fields.map(f=><section key={f.key} className="import-field"><label className="check-label"><input type="checkbox" disabled={!!importSubmission.current?.submitted} checked={!!choices[f.key]} onChange={e=>setChoices({...choices,[f.key]:e.target.checked})}/><strong>{f.title}</strong>{f.conflict&&<span className="warning">Different values</span>}</label><div className="conflict-copies"><div><p className="eyebrow">KEEP ACCOUNT COPY</p><pre>{typeof f.current==='string'?f.current||'(empty)':JSON.stringify(f.current,null,2)}</pre></div><div><p className="eyebrow">INCOMING COPY</p><pre>{typeof f.incoming==='string'?f.incoming||'(empty)':JSON.stringify(f.incoming,null,2)}</pre></div></div></section>)}<button className="primary" disabled={importPending} onClick={()=>void applyImport()}>{importPending?'Applying reviewed import…':importSubmission.current?.submitted?'Retry reviewed import':'Apply selected fields'}</button></Modal>
    <Modal open={reviewQueue} title="Review pending changes" onClose={()=>setReviewQueue(false)}><p>These changes have not been confirmed saved. For a curriculum conflict, compare both versions before replacing account topology.</p>{view.queue.filter(q=>q.conflict||q.error).map(q=><section className="import-field" key={q.operation.requestId}><h3>{q.operation.kind}</h3><p className="warning">{q.error??q.conflict?.message}</p><div className="conflict-copies"><div><h4>Your change</h4><pre>{JSON.stringify(q.operation.payload,null,2)}</pre></div><div><h4>Latest account copy</h4><pre>{JSON.stringify(q.conflict?.current,null,2)}</pre></div></div><button onClick={()=>void store.resolveOperation(q.operation.requestId,false)}>Keep account copy</button>{q.conflict?.revision&&<button onClick={()=>void store.resolveOperation(q.operation.requestId,true)}>Apply my reviewed change</button>}</section>)}</Modal>
  </div>;
}
function StageTabs({tab,onChange}:{tab:Tab;onChange:(tab:Tab)=>void}){const tabs:Tab[]=['brief','self-check','notes'];return <div className="stage-tabs" role="tablist" aria-label="Stage workspace">{tabs.map((t,i)=><button key={t} id={`tab-${t}`} role="tab" aria-selected={t===tab} aria-controls={`panel-${t}`} tabIndex={t===tab?0:-1} onClick={()=>onChange(t)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const index=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;onChange(tabs[index]);document.getElementById(`tab-${tabs[index]}`)?.focus();}}}>{t==='self-check'?'Self-check':t[0].toUpperCase()+t.slice(1)}</button>)}</div>;}
function GateDetails({node,state}:{node:TrailNode;state:NonNullable<ReturnType<AccountStore['getSnapshot']>['state']>}){return <><h2>{gateState(node,state.graph,state.learning).label}</h2><p className="muted">All three signals on each prerequisite must reach {LABELS[node.threshold]}. Telemetry opens the self-test; it does not certify mastery.</p><ul>{node.prerequisites.map(id=>{const n=state.graph.nodes.find(n=>n.id===id);return <li key={id}>{n?.title??'Unavailable prerequisite'}{n?.archived||!n?.placed?' — unavailable':''}</li>;})}</ul><dl><dt>Rebuild</dt><dd>Create the server–client pair again from a blank start.</dd><dt>Explain</dt><dd>Describe discovery, invocation, transport, and the server’s authority boundary.</dd><dt>Diagnose</dt><dd>Read one failure and identify the layer that produced it.</dd><dt>Decide</dt><dd>Choose a route based on the uncertainty you need to resolve.</dd></dl></>;}
