export function Deferred({open,onChange}:{open:boolean;onChange:(open:boolean)=>void}){
  const items=[
    ['Real project data','Actual research inputs and results beyond toy or sanitized examples.','Define what the server may read and return before exposing data.','When the data boundary is understood.','PySR and Py-Mynyra groundwork.'],
    ['Docker / HTTP','Packaging a runtime and choosing a network transport are separate decisions.','Neither is required to understand local stdio.','When a deployment needs repeatable packaging or a network boundary.','Possibly AI-host, PySR, or Py-Mynyra after the local design is stable.'],
    ['SSH / synchronization','Reaching another machine and keeping selected files aligned.','The local exercise requires neither.','When a workflow intentionally spans machines.','Potentially PySR or Py-Mynyra; not the Consolidation loop.'],
    ['Credentials','Authentication material for protected services.','The toy lab does not need secrets.','When a chosen service requires authentication and a safe secret-handling plan exists.','Only a route that connects to a protected service.'],
    ['Write-capable tools','Actions that change files, services, or external state.','Writes expand validation, approvals, and recovery responsibilities.','After the scope deliberately includes a bounded mutation and recovery path.','A future expansion; no current route requires it.'],
  ];
  return <details className="deferred" open={open} onToggle={e=>{if(e.currentTarget.open!==open)onChange(e.currentTarget.open);}}><summary><span className="eyebrow">DEFERRED</span> When these become relevant</summary><p>Deliberate later decisions, not missing steps or an activation checklist.</p><div className="deferred-grid">{items.map(([title,what,why,when,routes])=><article key={title}><h3>{title}</h3><dl><dt>What it means</dt><dd>{what}</dd><dt>Why later</dt><dd>{why}</dd><dt>Revisit when</dt><dd>{when}</dd><dt>Relevant routes</dt><dd>{routes}</dd></dl></article>)}</div><p><strong>Consolidation stays small:</strong> one local exercise, toy inputs, and no infrastructure expansion.</p></details>;
}
export function ProjectScenario(){return <section className="project-scenario"><span className="eyebrow">ROUTE D · PROJECT SCENARIO</span><h3>From the toy lab to a useful capability</h3><p>“Bring me up to date on Py-Mynyra.” A read-only tool grounded in reviewed project records—not an AI model inside the server.</p><ol className="checkpoint-list"><li><strong>Sourced project briefing</strong><p>A curated index, Python reader, diagnostic CLI, and separate stdio adapter expose <code>get_project_state()</code>. The model supplies no paths or arguments.</p></li><li><strong>Prototype evidence · 15 September 2026</strong><p>The source scenario records 95 domain tests, 4 adapter tests, and an SDK client discovering and calling the tool. These are historical prototype results, not tests run by this app or a learner score.</p></li><li><strong>Next question · connect one AI host</strong><p>Use documented, removable stdio configuration. Judge what context a briefing restores and what remains missing. Persistent host integration is not claimed by this checkpoint.</p></li></ol><details><summary>Trace the responsibility boundaries</summary><p>Application + client → stdio → MCP adapter → bounded reader → curated index and source records. The adapter rejects unexpected arguments; the reader enforces its file boundary. Hashes identify bytes, not semantic truth or complete history.</p></details><details><summary>What the checkpoint does not prove</summary><p>This is a project scenario, not a production release, full project history, or your personal progress. No orders, credentials, private data, spending, new research batch, or write-capable automation is included.</p></details></section>;}
