import { useLayoutEffect, useRef, useState, type CSSProperties } from 'react';
import { activeNodes,gateState,LENSES,LEVELS,SIGNALS,type Graph,type Lens,type Snapshot,type TrailNode } from '../domain';
import type { AccountStore } from '../store';
const CONTOURS=['M-40 104C88 20 191 62 286 121S484 203 590 121 802 24 1040 92','M-46 137C80 55 186 91 278 150S477 233 594 153 804 56 1047 126','M-58 176C75 93 171 129 271 185S466 267 599 190 818 94 1056 166','M-65 221C69 139 166 170 262 224S461 305 609 232 823 135 1060 211','M-70 276C57 195 157 219 252 270S454 349 621 281 837 183 1066 262','M-68 339C41 257 147 261 244 311S449 395 632 341 850 245 1061 323','M-53 409C32 327 139 317 237 363S446 445 643 411 858 317 1048 388','M-32 480C36 407 137 378 238 418S452 493 650 481 865 395 1031 454','M-5 545C62 486 148 445 251 479S465 548 665 543 872 479 1015 519','M44 604C100 552 173 517 278 535S491 594 687 595 878 547 988 572'];
export function Terrain(){return <svg className="terrain" viewBox="0 0 1000 620" preserveAspectRatio="none" aria-hidden="true">{CONTOURS.map(d=><path key={d} d={d}/>)}</svg>;}
export function LensToolbar({state,lens,onChange}:{state:Snapshot;lens:Lens;onChange:(id:Lens)=>void}){
  const ref=useRef<HTMLDivElement>(null),[highlight,setHighlight]=useState<CSSProperties>({});
  useLayoutEffect(()=>{const el=ref.current!;const measure=()=>{const active=el.querySelector<HTMLElement>('[aria-pressed="true"]');if(active)setHighlight({width:active.offsetWidth,height:active.offsetHeight,transform:`translate(${active.offsetLeft}px,${active.offsetTop}px)`});};const observer=new ResizeObserver(measure);observer.observe(el);el.querySelectorAll('button').forEach(b=>observer.observe(b));measure();return()=>observer.disconnect();},[lens]);
  const stages=activeNodes(state.graph).filter(n=>n.kind==='stage'),definition=LENSES.find(l=>l.id===lens)!;
  const practiced=lens==='overview'?0:stages.filter(n=>state.learning.mastery[n.id]?.[lens]?.value!=='not_yet').length;
  const independent=lens==='overview'?0:stages.filter(n=>state.learning.mastery[n.id]?.[lens]?.value==='independent').length;
  const next=lens==='overview'?stages.find(n=>SIGNALS.some(s=>state.learning.mastery[n.id]?.[s]?.value==='not_yet')):stages.find(n=>state.learning.mastery[n.id]?.[lens]?.value!=='independent');
  return <div className={`map-toolbar signal-${lens}`}><div className="toolbar-heading"><span className="eyebrow">MAP LENS</span><p>Choose what the terrain reveals</p></div><div ref={ref} className="lens-switch" role="group" aria-label="Map lenses"><span className="moving-highlight" style={highlight}/>{LENSES.map(l=><button key={l.id} aria-pressed={lens===l.id} onClick={()=>onChange(l.id)}>{l.label}</button>)}</div><div className="lens-readout"><span className="eyebrow">ACTIVE LENS</span><div><strong>{definition.label}</strong><p>{definition.purpose}</p></div><p className="lens-metrics">{lens!=='overview'&&`${practiced} of ${stages.length} practiced · ${independent} of ${stages.length} independent · `}{next?`Next: ${next.title}`:lens==='overview'?'Explore your gates and choose a next route.':'All placed stages independent.'}</p></div></div>;
}
export function TrailMap({state,selected,lens,onSelect,editing,store}:{state:Snapshot;selected:string|null;lens:Lens;onSelect:(id:string)=>void;editing:boolean;store:AccountStore}){
  const ref=useRef<HTMLDivElement>(null),[paths,setPaths]=useState<{key:string;d:string;branch:boolean;ready:boolean}[]>([]),[drag,setDrag]=useState<{id:string;x:number;y:number}|null>(null);
  const nodes=activeNodes(state.graph),stages=nodes.filter(n=>n.kind==='stage');
  const dragOrigin=useRef<{clientX:number;clientY:number;x:number;y:number;revision:number}|null>(null),suppressClick=useRef(false);
  useLayoutEffect(()=>{const el=ref.current!;let frame=0;const draw=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const bounds=el.getBoundingClientRect();const result=[];for(const e of state.graph.edges){
    const from=el.querySelector<HTMLElement>(`[data-port="${e.source}"]`),to=el.querySelector<HTMLElement>(`[data-port="${e.target}"]`);if(!from||!to)continue;
    const a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),x1=a.left+a.width/2-bounds.left,y1=a.top+a.height/2-bounds.top,x2=b.left+b.width/2-bounds.left,y2=b.top+b.height/2-bounds.top;
    const target=nodes.find(n=>n.id===e.target)!,source=nodes.find(n=>n.id===e.source)!;
    const branch=target.kind==='route',ready=source.kind==='gate'?gateState(source,state.graph,state.learning).ready:source.kind==='stage'&&(lens==='overview'?SIGNALS.every(s=>state.learning.mastery[source.id]?.[s]?.value!=='not_yet'):state.learning.mastery[source.id]?.[lens]?.value!=='not_yet');
    const d=Math.abs(x2-x1)<20?`M${x1} ${y1}L${x2} ${y2}`:`M${x1} ${y1}C${x1+(x2-x1)*.4} ${y1} ${x1+(x2-x1)*.65} ${y2} ${x2} ${y2}`;
    result.push({key:`${e.source}-${e.target}`,d,branch,ready});}setPaths(result);});};
    const observer=new ResizeObserver(draw);observer.observe(el);el.querySelectorAll('button').forEach(b=>observer.observe(b));draw();return()=>{observer.disconnect();cancelAnimationFrame(frame);};
  },[state.graph,state.learning,lens,drag]);
  const start=(event:React.PointerEvent<HTMLButtonElement>,n:TrailNode)=>{if(!editing||event.button!==0||getComputedStyle(ref.current!).display==='flex')return;event.currentTarget.setPointerCapture(event.pointerId);dragOrigin.current={clientX:event.clientX,clientY:event.clientY,x:n.x,y:n.y,revision:state.revisions.curriculum};suppressClick.current=false;store.setBusy('drag',true);setDrag({id:n.id,x:n.x,y:n.y});};
  const move=(event:React.PointerEvent<HTMLButtonElement>)=>{const origin=dragOrigin.current;if(!drag||!origin)return;const dx=event.clientX-origin.clientX,dy=event.clientY-origin.clientY;if(Math.hypot(dx,dy)<4&&!suppressClick.current)return;suppressClick.current=true;const b=ref.current!.getBoundingClientRect();setDrag({...drag,x:Math.max(5,Math.min(95,origin.x+dx/b.width*100)),y:Math.max(8,Math.min(90,origin.y+dy/b.height*100))});};
  const end=()=>{if(!drag)return;const origin=dragOrigin.current;setDrag(null);dragOrigin.current=null;store.setBusy('drag',false);if(!suppressClick.current||!origin)return;const g:Graph={...state.graph,nodes:state.graph.nodes.map(n=>n.id===drag.id?{...n,x:Math.round(drag.x),y:Math.round(drag.y)}:n)};void store.graph(g,origin.revision);};
  return <div className={`terrain-map ${editing?'is-editing':''}`} ref={ref} aria-label="Your personal learning trail"><Terrain/><svg className="trail-lines" aria-hidden="true">{paths.map(p=><path key={p.key} d={p.d} className={`${p.branch?'branch':'trail'} ${p.ready?'ready':''}`}/>)}</svg>
    {nodes.map(n=>{const index=stages.findIndex(s=>s.id===n.id),position=drag?.id===n.id?drag:n;return <button key={n.id} className={`trail-node ${n.kind} ${n.kind==='stage'&&index%2?'label-above':'label-below'}`} style={{'--x':`${position.x}%`,'--y':`${position.y}%`} as CSSProperties} aria-pressed={selected===n.id} onClick={()=>{if(suppressClick.current){suppressClick.current=false;return;}onSelect(n.id);}} onPointerDown={e=>start(e,n)} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{setDrag(null);dragOrigin.current=null;suppressClick.current=false;store.setBusy('drag',false);}}>
      <span className="node-symbol" data-port={n.id}>{n.kind==='stage'?<><svg viewBox="0 0 56 56" aria-hidden="true">{SIGNALS.map((s,i)=><g key={s}><circle cx="28" cy="28" r={23-i*5} className="ring-base"/><circle key={state.learning.mastery[n.id]?.[s]?.revision} cx="28" cy="28" r={23-i*5} pathLength="100" className={`ring signal-${s}`} style={{strokeDasharray:`${LEVELS.indexOf(state.learning.mastery[n.id]?.[s]?.value??'not_yet')*50} 100`}}/></g>)}</svg><span>{String(index).padStart(2,'0')}</span></>:n.kind==='gate'?<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M32 2 62 32 32 62 2 32Z M17 17 47 47 M47 17 17 47" className="gate-diamond"/></svg>:<span className="route-dot"/>}</span>
      <span className="node-label"><span className="eyebrow">{n.kind==='stage'?`STAGE ${String(index).padStart(2,'0')}`:`${n.kind.toUpperCase()} ${n.code}`}</span><strong>{n.title}</strong>{n.kind==='gate'&&<small>{gateState(n,state.graph,state.learning).label}</small>}</span>
    </button>;})}
    {!nodes.length&&<p className="empty">Your trail is empty. Open Edit trail to place a stage.</p>}
  </div>;
}
