import { useEffect,useState } from 'react';
import { activeNodes,automaticPositions,reorderNode,validateGraph,type Graph,type Kind,type Snapshot,type TrailNode } from '../domain';
import type { AccountStore } from '../store';
import { Modal } from './Modal';
export function TrailEditor({open,onClose,state,store}:{open:boolean;onClose:()=>void;state:Snapshot;store:AccountStore}){
  const [resetPreview,setResetPreview]=useState<Snapshot|null>(null);
  const [graph,setGraph]=useState<Graph>(state.graph),[revision,setRevision]=useState(state.revisions.curriculum),[selected,setSelected]=useState(state.graph.nodes[0]?.id??''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[message,setMessage]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{if(open){setGraph(structuredClone(state.graph));setRevision(state.revisions.curriculum);setMessage('');store.setBusy('trail-editor',true);}return()=>store.setBusy('trail-editor',false);},[open]);
  const node=graph.nodes.find(n=>n.id===selected);
  const stages=activeNodes(graph).filter(n=>n.kind==='stage');
  const update=(patch:Partial<TrailNode>)=>setGraph(g=>({...g,nodes:g.nodes.map(n=>n.id===selected?{...n,...patch}:n)}));
  const add=(kind:Kind)=>{const id=crypto.randomUUID();setGraph(g=>({...g,nodes:[...g.nodes,{id,kind,origin:null,code:null,title:`New ${kind}`,content:kind==='stage'?{objective:'',action:'',evidence:''}:kind==='route'?{choose:'',outcome:'',constraint:''}:{},order:g.nodes.length,x:50,y:50,placed:false,archived:false,threshold:'practicing',prerequisites:[]}]}));setSelected(id);};
  const connect=()=>{if(!from||!to){setMessage('Choose both ends of the connection.');return;}const next={...graph,edges:[...graph.edges,{source:from,target:to}],nodes:graph.nodes.map(n=>n.id===to?{...n,placed:true}:n)};const problem=validateGraph(next);if(problem){setMessage(problem);return;}setGraph(next);setMessage('Connection added to this draft.');};
  const save=async()=>{const problem=validateGraph(graph);if(problem){setMessage(problem);return;}setBusy(true);try{if(await store.graph(graph,revision))onClose();else setMessage('Not saved yet. Review pending changes in the account status panel; this editor draft remains here.');}finally{setBusy(false);}};
  const trash=graph.nodes.filter(n=>n.archived);
  const archiveSaved=!!state.graph.nodes.find(n=>n.id===node?.id)?.archived;
  const resetLayout=()=>{const positions=automaticPositions(graph);setGraph(g=>({...g,nodes:g.nodes.map(n=>positions[n.id]?{...n,...positions[n.id]}:n)}));setMessage('Automatic layout staged. Save the trail to keep it.');};
  return <Modal open={open} onClose={onClose} title="Edit your personal trail" className="trail-editor-modal"><p className="muted">Your copy is private. Stable IDs keep notes attached when titles or positions change. Save applies the whole topology atomically; another browser’s conflicting edit requires review.</p>
    <div className="editor-actions"><button onClick={()=>add('stage')} disabled={graph.nodes.length>=200}>+ Stage</button><button onClick={()=>add('gate')} disabled={graph.nodes.length>=200}>+ Gate</button><button onClick={()=>add('route')} disabled={graph.nodes.length>=200}>+ Route</button><button onClick={resetLayout}>Reset layout</button><span>{graph.nodes.length}/200 nodes · {graph.edges.length}/400 connections</span></div>
    <div className="builder-layout"><nav aria-label="Trail elements"><h3>Placed</h3>{activeNodes(graph).map(n=><button key={n.id} aria-pressed={selected===n.id} onClick={()=>setSelected(n.id)}>{n.kind==='stage'?String(stages.findIndex(s=>s.id===n.id)).padStart(2,'0'):`${n.kind} ${n.code??'new'}`} · {n.title}</button>)}<h3>Unplaced</h3><p className="small">Connect drafts to the active trail when ready.</p>{graph.nodes.filter(n=>!n.placed&&!n.archived).map(n=><button key={n.id} aria-pressed={selected===n.id} onClick={()=>setSelected(n.id)}>{n.title}</button>)}<h3>Trash · {trash.length}</h3>{trash.map(n=><button key={n.id} aria-pressed={selected===n.id} onClick={()=>setSelected(n.id)}>{n.title}</button>)}</nav>
      {node?<section className="builder-fields"><h3>{node.kind} {node.code??'draft'}</h3><label>Title<input value={node.title} maxLength={120} onChange={e=>update({title:e.target.value})}/></label>
        {Object.entries(node.kind==='stage'?{objective:'Objective',action:'Next action',evidence:'Success evidence'}:node.kind==='route'?{choose:'Choose when',outcome:'Outcome',constraint:'Constraint'}:{}).map(([key,label])=><label key={key}>{label}<textarea rows={3} maxLength={4000} value={node.content[key]??''} onChange={e=>update({content:{...node.content,[key]:e.target.value}})}/></label>)}
        {node.kind==='gate'&&<><label>Minimum mastery<select value={node.threshold} onChange={e=>update({threshold:e.target.value as 'practicing'|'independent'})}><option value="practicing">Practicing · with help</option><option value="independent">Independent · without help</option></select></label><fieldset><legend>Prerequisite stages</legend><p className="small">Each needs all three signals at the threshold and an upstream connection to this gate. An archived prerequisite stays unavailable.</p>{graph.nodes.filter(n=>n.kind==='stage').map(n=><label className="check-label" key={n.id}><input type="checkbox" checked={node.prerequisites.includes(n.id)} onChange={e=>update({prerequisites:e.target.checked?[...node.prerequisites,n.id]:node.prerequisites.filter(id=>id!==n.id)})}/>{n.title}{n.archived?' (archived)':''}</label>)}</fieldset></>}
        <div className="position-fields"><label>Order<input type="number" min={0} max={10000} value={node.order} onChange={e=>update({order:Number(e.target.value)})}/></label><label>Horizontal %<input type="number" min={5} max={95} value={node.x} onChange={e=>update({x:Number(e.target.value)})}/></label><label>Vertical %<input type="number" min={8} max={90} value={node.y} onChange={e=>update({y:Number(e.target.value)})}/></label></div>
        <div className="editor-actions"><button onClick={()=>setGraph(g=>reorderNode(g,node.id,-1))}>Earlier</button><button onClick={()=>setGraph(g=>reorderNode(g,node.id,1))}>Later</button><button onClick={()=>update({x:Math.max(5,node.x-2)})}>← Move</button><button onClick={()=>update({x:Math.min(95,node.x+2)})}>Move →</button><button onClick={()=>update({y:Math.max(8,node.y-2)})}>↑</button><button onClick={()=>update({y:Math.min(90,node.y+2)})}>↓</button></div>
        <label className="check-label"><input type="checkbox" checked={node.placed} onChange={e=>update({placed:e.target.checked})}/>Place on trail (connect new drafts first)</label>
        {node.archived?<><button onClick={()=>{const next={...graph,nodes:graph.nodes.map(n=>n.id===node.id?{...n,archived:false}:n)},problem=validateGraph(next);if(problem){setMessage(`Repair connections before restoring: ${problem}`);return;}setGraph(next);setMessage('Restored valid saved connections. Connections to archived endpoints remain inactive.');}}>Restore from Trash</button>{!archiveSaved&&<p className="small">Save the trail to archive this element first. Reopen Trash to permanently delete it.</p>}<button className="danger" disabled={!archiveSaved} onClick={()=>setConfirm(`delete:${node.id}`)}>Permanently delete…</button></>:<button onClick={()=>update({archived:true})}>Archive to Trash</button>}
      </section>:<p>Select an element or add a stage.</p>}
    </div>
    <section className="connection-editor"><h3>Connections</h3><div className="position-fields"><label>From<select value={from} onChange={e=>setFrom(e.target.value)}><option value="">Choose source</option>{graph.nodes.filter(n=>!n.archived&&n.kind!=='route').map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><label>To<select value={to} onChange={e=>setTo(e.target.value)}><option value="">Choose destination</option>{graph.nodes.filter(n=>!n.archived).map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><button onClick={connect}>Connect →</button></div><ul className="connection-list">{graph.edges.map((e,i)=><li key={`${e.source}:${e.target}`}><span>{graph.nodes.find(n=>n.id===e.source)?.title} → {graph.nodes.find(n=>n.id===e.target)?.title}</span><button onClick={()=>setGraph(g=>({...g,edges:g.edges.filter((_,j)=>i!==j)}))} aria-label={`Remove connection ${i+1}`}>Remove</button></li>)}</ul></section>
    {confirm.startsWith('delete:')&&<section className="confirmation" role="alert"><h3>Delete from Trash permanently?</h3><p>This removes the node and its notes, mastery, and incident connections when you save. Repair every gate that depends on it first.</p><button className="danger" onClick={()=>{const id=confirm.slice(7);if(graph.nodes.some(n=>n.prerequisites.includes(id))){setMessage('Remove this stage from every gate prerequisite list and save that repair before deleting.');setConfirm('');return;}setGraph(g=>({...g,nodes:g.nodes.filter(n=>n.id!==id),edges:g.edges.filter(e=>e.source!==id&&e.target!==id)}));setConfirm('');}}>Confirm deletion</button><button onClick={()=>setConfirm('')}>Keep it</button></section>}
    <p role="status">{message}</p><footer className="editor-actions"><button className="primary" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save trail'}</button><button onClick={onClose}>Close without saving this draft</button><button className="danger" disabled={busy} onClick={async()=>{if(!(await store.flush())){setMessage('Resolve pending saves before previewing a reset.');return;}setResetPreview(structuredClone(store.getSnapshot().state!));setConfirm('reset');}}>Reset private curriculum…</button></footer>
    {confirm==='reset'&&resetPreview&&<section className="confirmation"><h3>Reset your private curriculum?</h3><p>This will replace {resetPreview.graph.nodes.length} nodes, {resetPreview.graph.edges.length} connections, all mastery, {Object.keys(resetPreview.learning.notes).length} notes, and saved navigation with the neutral template. Export your context from the account menu first. Other accounts are unaffected.</p><button className="danger" disabled={busy} onClick={async()=>{setBusy(true);try{const s=resetPreview;if(await store.enqueue('reset',s.revisions.curriculum,{confirmation:'RESET MY TRAIL',learningRevision:s.revisions.learning,uiRevision:s.revisions.ui}))onClose();else setMessage('Reset was not applied. Review pending changes, then reopen a fresh reset preview.');}finally{setBusy(false);}}}>RESET MY TRAIL</button><button onClick={()=>setConfirm('')}>Cancel reset</button></section>}
  </Modal>;
}
